from setuptools import setup, find_packages

setup(
    name="deepseek-verilog-finetune",
    version="0.1.0",
    description="DeepSeek R1 Fine-tuning Pipeline for Verilog Code Generation",
    author="VerilogDeepSeekR1 Team",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    python_requires=">=3.8",
    install_requires=[
        "torch>=2.0.0",
        "transformers>=4.36.0",
        "accelerate>=0.25.0",
        "datasets>=2.14.0",
        "evaluate>=0.4.0",
        "deepspeed>=0.12.0",
        "wandb>=0.16.0",
        "trl>=0.7.0",
        "peft>=0.7.0",
        "bitsandbytes>=0.41.0",
        "huggingface_hub>=0.19.0",
        "tokenizers>=0.15.0",
        "numpy>=1.24.0",
        "pandas>=2.0.0",
        "scikit-learn>=1.3.0",
        "tqdm>=4.65.0",
        "pyyaml>=6.0",
    ],
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
)