model:
  name: "deepseek-ai/deepseek-r1-distill-qwen-32b"
  torch_dtype: "bfloat16"
  device_map: "auto"
  trust_remote_code: true

lora:
  r: 64
  lora_alpha: 32
  target_modules: ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]
  lora_dropout: 0.1
  bias: "none"
  task_type: "CAUSAL_LM"

training:
  output_dir: "./checkpoints"
  num_train_epochs: 3
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  gradient_accumulation_steps: 8
  eval_accumulation_steps: 4
  learning_rate: 2e-5
  weight_decay: 0.1
  warmup_steps: 500
  logging_steps: 10
  save_steps: 500
  eval_steps: 500
  save_total_limit: 3
  load_best_model_at_end: true
  metric_for_best_model: "eval_loss"
  greater_is_better: false
  dataloader_pin_memory: true
  dataloader_num_workers: 4
  remove_unused_columns: false
  label_names: ["labels"]
  
optimization:
  optim: "adamw_torch"
  adam_beta1: 0.9
  adam_beta2: 0.95
  adam_epsilon: 1e-8
  max_grad_norm: 1.0
  lr_scheduler_type: "cosine"
  
mixed_precision:
  bf16: true
  bf16_full_eval: true
  
deepspeed:
  config_file: "./configs/deepspeed_config.json"
  
logging:
  report_to: ["wandb"]
  run_name: "deepseek-verilog-sft"
  
evaluation:
  evaluation_strategy: "steps"
  eval_steps: 500
  do_eval: true